[package]
name = "veeder-pot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
csv = "1.1.6"
chrono = "0.4.22"
tabular = "0.2.0"